### ISSUE TITLE
use VersionParsing.jl to parse version numbers

### ISSUE THREAD

**Issue by stevengj** [JuliaPackaging/Git.jl#19]
I notice that you have some parsing machinations for handling foreign version numbers via VersionNumber(string). You might try vparse from https://github.com/stevengj/VersionParsing.jl instead.

**Comment by crstnbr** [comment]
Based on https://github.com/stevengj/VersionParsing.jl/blob/master/REQUIRE this would require a mimum Compat Compat 0.62.0. In the process of #21 we have to increase to 0.47.0. anyway. Maybe we should increase to 0.62.0 right away?

**Comment by stevengj** [comment]
No, in general you should list the Compat version that your own code relies upon.   The Pkg system is responsible for merging that with the requirements of your dependencies.

**Comment by crstnbr** [comment]
I see, thanks.

**Comment by crstnbr** [comment]
See https://github.com/JuliaPackaging/Git.jl/pull/21/commits/932699bcd4c5691208efca17f5211daf83cd227c.

**Comment by ararslan** [comment]
Fixed by #21.
