### ISSUE TITLE
Julia 1.0 support

### ISSUE THREAD

**Issue by crstnbr** [JuliaPackaging/Git.jl#20]
I'd love to have this working in 1.0!

**Comment by crstnbr** [comment]
I started to port it to 1.0 locally. However, there are one or two places where I'm not sure what to do. Should I make a WIP PR (and hopefully get some Input from you @ararslan ?)

**Comment by ararslan** [comment]
You're welcome to pick up where I left off with those changes; I have no plans to revisit that PR.

**Comment by crstnbr** [comment]
Note, btw, that one can currently add this package on 1.0 although it's not working at all.

**Comment by ararslan** [comment]
Fixed by #21.
