### ISSUE TITLE
AppVeyor tests are ridiculously slow

### ISSUE THREAD

**Issue by ararslan** [JuliaPackaging/Git.jl#3]
As of this writing, the Travis tests take about 4 minutes each while the AppVeyor tests take about 45 minutes each. Generally speaking Travis seems to be faster than AppVeyor, but this is pretty ridiculous. Surely there must be something we can do to improve that, be it by changing something with the AppVeyor configuration or finding a way to make the code run faster on Windows.

Windows people: Is command line Git really slow on Windows? Is there any way to tell where the bottleneck is that's affecting Windows (but apparently not other platforms)?

People who understand AppVeyor: The majority of the time on AppVeyor seems to be spent running the actual tests rather than spawning and shutting down the VMs, but is there anything we can do in the YAML or in the project settings to get things running a little faster?

**Comment by nalimilan** [comment]
Does it take about the same time on a local Windows box? I think starting lots of `git` processes is way slower there, this was one of the motivations for moving to libgit2. If so, we can't do much to avoid this.

**Comment by ararslan** [comment]
I guess I could test it on my Windows VM but literally everything takes forever on that so it wouldn't be a very accurate test.

Good to know about libgit2. I'm kind of concerned about increasing the coverage (which is currently pretty bad) by adding more tests because the AppVeyor tests are pretty close to timing out as it is.

**Comment by ararslan** [comment]
I don't really know what did it (I assume it was some @tkelman magic) but the AppVeyor tests run in about 12-16 minutes now. That's a huge improvement and is good enough for me. 😉

**Comment by tkelman** [comment]
I think @FeodorFitsner was going to migrate the VM's to a new environment at some point, guess they're way faster now.
